
export const GET_RESTURANT_REQUEST = 'GET_RESTURANT_REQUEST';
export const GET_RESTURANT_SUCCESS = 'GET_RESTURANT_SUCCESS';
export const GET_RESTURANT_ERROR = 'GET_RESTURANT_ERROR';

export const UPDATE_ALBUMS_REQUEST = 'UPDATE_ALBUMS_REQUEST';
export const UPDATE_ALBUMS_SUCCESS = 'UPDATE_ALBUMS_SUCCESS';
export const UPDATE_ALBUMS_ERROR = 'UPDATE_ALBUMSS_ERROR';
